[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"

fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 5000

[invariant]
runs = 256
depth = 100
fail_on_revert = true

[rpc_endpoints]
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
optimism = { key = "${OPTIMISM_SCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}" }
base = { key = "${BASE_SCAN_API_KEY}", url = "${BASE_ETHERSCAN_VERIFIER_URL}" }
